[package]
name = "budget-book"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }
